[Improvement] - Readme and Rubric
betrybe/sd-0x-mongodb-dataflights pull request #7
Opened 2021-03-15 12:11 UTC by LizzardMedeiros

- [x] Ajustes no Readme
- [x] Criação da Rubrica 

[Rubrica](https://github.com/betrybe/sd-0x-mongodb-dataflights-rubric/pull/1)
[Testes](https://github.com/betrybe/sd-0x-project-mongodb-dataflights-tests)

2021-03-17 21:13 UTC, roziscoding approved these changes

2021-03-18 02:06 UTC, GabrielCoruja requested changes

2021-03-18 02:06 UTC, GabrielCoruja commented on README.md
> +  * `git clone https://github.com/tryber/sd-0x-project-mongodb-dataflights.git`.
Não realizar esta alteração, o link do clone já foi alterado para o comando correto, sem o **project**

2021-03-18 02:06 UTC, GabrielCoruja commented on README.md
> +Você deve criar uma pasta chamada `challenges`, contendo dentro dela arquivos no formato `desafioX.js` onde `X` é o número do requisito.
Colocar "na raíz do projeto" deixa de maneira mais explícita, onde deve ser criada a pasta **challenges**

2021-03-18 02:06 UTC, GabrielCoruja commented on README.md
> +#### 12 - Retorne os documentos em que o campo `aeroportoDestino.pais` seja igual a `BRASIL`, `ARGENTINA` ou `CHILE`.
Retornar para "a quantidade de", pois fica melhor descrito que deve ser feita uma contagem de documentos.
Se colocar "Retorne os documentos" não fica explícito que deve ser feita uma contagem.

2021-03-18 02:06 UTC, GabrielCoruja commented on README.md
> +#### 13 - Retorne os documentos em que o campo `aeroportoDestino.continente` não seja igual a `EUROPA`, `ÁSIA` e `OCEANIA`.
Retornar para "a quantidade de", pois fica melhor descrito que deve ser feita uma contagem de documentos.
Se colocar "Retorne os documentos" não fica explícito que deve ser feita uma contagem.

2021-03-18 02:06 UTC, GabrielCoruja commented on package.json
>  }
Bom trabalho, as alterações estão melhorando o projeto @LizzardMedeiros

2021-03-18 12:08 UTC, GabrielCoruja approved these changes

2021-03-22 19:31 UTC, closed without merging